### ISSUE TITLE
Initialize `zn_scene::unmap_focused_view_listener` on create `zn_scene`

### ISSUE THREAD

**Issue by Aki-7** [zigen-project/zen#153]
## Reproduction

- Start `zen-desktop` with no argument
- Do not start any view
- Stop `zen-desktop` gracefully (<alt> + q)
- Segmentation fault

## Cause
- `zn_scene::unmap_focused_view_listener` is not initialized in `zn_scene_create`

**Comment by watasuke102** [comment]
solved by #168
